apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: sample-mongodb-backup
  namespace: demo
spec:
  schedule: "*/2 * * * *"
  repository:
    name: s3-repo
    namespace: demo
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mongo-sh
  retentionPolicy:
    name: keep-last-5
    keepLast: 5
    prune: true
