apiVersion: stash.appscode.com/v1beta1
kind: BackupBlueprint
metadata:
  name: mongodb-backup-template
spec:
  # ============== Blueprint for Repository ==========================
  backend:
    s3:
      endpoint: us-east-1.linodeobjects.com
      bucket: abusayed
      prefix: mongodb-backup/${TARGET_NAMESPACE}/${TARGET_APP_RESOURCE}/${TARGET_NAME}
      region: us-east-1
    storageSecretName: s3-secret
  # ============== Blueprint for BackupConfiguration =================
  schedule: "*/5 * * * *"
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true