apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mg-sh
  namespace: demo
spec:
  arbiter:
    podTemplate:
      spec:
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
  clusterAuthMode: keyFile
  shardTopology:
    configServer:
      podTemplate:
        spec:
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 400Mi
      replicas: 3
      storage:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        # storageClassName: standard
    mongos:
      podTemplate:
        spec:
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 400Mi
      replicas: 3
    shard:
      podTemplate:
        spec:
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 400Mi
      replicas: 3
      shards: 2
      storage:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        # storageClassName: standard
  sslMode: disabled
  storageEngine: wiredTiger
  storageType: Durable
  terminationPolicy: WipeOut
  version: 7.0.4
