apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mongo-ca-issuer
  namespace: demo
spec:
  ca:
    secretName: mongo-ca

# apiVersion: cert-manager.io/v1
# kind: Issuer
# metadata:
#   name: mg-new-issuer
#   namespace: demo
# spec:
#   ca:
#     secretName: mongo-new-ca