apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mg-st
  namespace: demo
spec:
  version: "7.0.4"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1G
  # sslMode: requiredSSL
  # tls:
  #   issuerRef:
  #     apiGroup: "cert-manager.io"
  #     kind: Issuer
  #     name: mongo-ca-issuer
  terminationPolicy: WipeOut
  # monitor:
  #   agent: prometheus.io/operator
  #   prometheus:
  #     serviceMonitor:
  #       labels:
  #         release: prometheus
  #       interval: 10s
  # configSecret:
  #   name: mg-configuration  