apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mg-rep
  namespace: demo
spec:
  version: "7.0.4"
  replicaSet: 
    name: "replicaset"
  replicas: 2
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1G
  # sslMode: requireSSL
  # tls:
  #   issuerRef:
  #     apiGroup: "cert-manager.io"
  #     kind: Issuer
  #     name: mongo-ca-issuer    
  terminationPolicy: WipeOut
  # monitor:
  #   agent: prometheus.io/operator
  #   prometheus:
  #     serviceMonitor:
  #       labels:
  #         release: prometheus
  #     exporter:
  #       args: ["--compatible-mode"]  