apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mg-rep
  namespace: demo
spec:
  version: "4.4.6"
  replicaSet: 
    name: "replicaset"
  replicas: 2
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  sslMode: disabled 
  terminationPolicy: WipeOut