apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mg-standalone-1
  namespace: demo
spec:
  version: "4.4.6"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  sslMode: disabled
  terminationPolicy: WipeOut
  # monitor:
  #   agent: prometheus.io/operator
  #   prometheus:
  #     serviceMonitor:
  #       labels:
  #         release: prometheus
  #       interval: 10s