apiVersion: catalog.kubeware.dev/v1alpha1
kind: MongoDBBinding
metadata:
  name: mongo-binding
  namespace: kube
  annotations:
    gateway.networking.k8s.io/name: kwg
    gateway.networking.k8s.io/namespace: gateway
spec:
  sourceRef:
    namespace: demo
    name: mongo