apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: update
  namespace: demo
spec:
  type: UpdateVersion
  databaseRef:
    name: mg-rep
  updateVersion:
    targetVersion: 4.4.25
  readinessCriteria:
    oplogMaxLagSeconds: 20
    objectsCountDiffPercentage: 10
  timeout: 5m
  apply: IfReady