apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  creationTimestamp: null
  name: secret-provider-class
  namespace: demo
spec:
  parameters:
    objects: |
      - objectName: mongodb-creds-password
        secretKey: password
        secretPath: /k8s.ff47fbf8-bf7f-4dbf-84a0-18e19494415a.mongodb.demo.mongodb-secret-engine/creds/k8s.ff47fbf8-bf7f-4dbf-84a0-18e19494415a.demo.mongodb-readwrite-role
      - objectName: mongodb-creds-username
        secretKey: username
        secretPath: /k8s.ff47fbf8-bf7f-4dbf-84a0-18e19494415a.mongodb.demo.mongodb-secret-engine/creds/k8s.ff47fbf8-bf7f-4dbf-84a0-18e19494415a.demo.mongodb-readwrite-role
    roleName: k8s.ff47fbf8-bf7f-4dbf-84a0-18e19494415a.demo.srb-demo-secret-role-binding
    vaultAddress: http://vault.demo:8200
    vaultSkipTLSVerify: "true"
  provider: vault