apiVersion: engine.kubevault.com/v1alpha1
kind: SecretRoleBinding
metadata:
  name: secret-role-binding
  namespace: demo
spec:
  roles:
    - kind: MongoDBRole
      name: mongodb-readwrite-role
  subjects:
    - kind: ServiceAccount
      name: app-service-account
      namespace: demo