apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: simple-2
  namespace: demo
  labels:
    archiver: "true"  
spec:
  version: "4.4.26"
  shardTopology:
    configServer:
      replicas: 2
      storage:
        resources:
          requests:
            storage: 5Gi
        # storageClassName: longhorn
        # storageClassName: "standard"             
        storageClassName: "linode-block-storage"             
    mongos:
      replicas: 1
    shard:
      replicas: 2
      shards: 2
      storage:
        resources:
          requests:
            storage: 5Gi
        # storageClassName: longhorn
        # storageClassName: "standard"     
        storageClassName: "linode-block-storage"                
  # terminationPolicy: WipeOut
  # monitor:
  #   agent: prometheus.io/operator
  #   prometheus:
  #     serviceMonitor:
  #       labels:
  #         release: prometheus
  #     exporter:
  #       args: ["--compatible-mode"]  
  # sslMode: requireSSL
  # tls:
  #   issuerRef:
  #     apiGroup: "cert-manager.io"
  #     kind: Issuer
  #     name: mongo-ca-issuer        
  # monitor:
  #   agent: prometheus.io/builtin
  #   prometheus:
  #     exporter:
  #       args: ["--compatible-mode"]      