apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mg-shard
  namespace: demo
spec:
  version: "5.0.3"
  shardTopology:
    configServer:
      replicas: 3
      storage:
        resources:
          requests:
            storage: 250Mi
        storageClassName: standard
    mongos:
      replicas: 1
    shard:
      replicas: 3
      shards: 2
      storage:
        resources:
          requests:
            storage: 250Mi
        storageClassName: standard