apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: simple
  namespace: demo
spec:
  version: "7.0.4"
  shardTopology:
    configServer:
      replicas: 2
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
    mongos:
      replicas: 1
    shard:
      replicas: 2
      shards: 1
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
  # monitor:
  #   agent: prometheus.io/operator
  #   prometheus:
  #     serviceMonitor:
  #       labels:
  #         release: prometheus
  #     exporter:
  #       args: ["--compatible-mode"]  
  # sslMode: requireSSL
  # tls:
  #   issuerRef:
  #     apiGroup: "cert-manager.io"
  #     kind: Issuer
  #     name: mongo-ca-issuer        
  # monitor:
  #   agent: prometheus.io/builtin
  #   prometheus:
  #     exporter:
  #       args: ["--compatible-mode"]      