apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mg-sh
  namespace: demo
spec:
  version: "4.4.6"
  shardTopology:
    configServer:
      replicas: 3
      storage:
        resources:
          requests:
            storage: 250Mi
        storageClassName: standard
    mongos:
      replicas: 1
    shard:
      replicas: 3
      shards: 2
      storage:
        resources:
          requests:
            storage: 250Mi
        storageClassName: standard