apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: mg
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: MongoDB
    namespace: demo
    name: simple
  backends:
    - name: s3-backend
      storageRef:
        namespace: demo
        name: s3-storage
      retentionPolicy:
        name: rp
        namespace: demo    
  sessions:
    - name: frequent
      scheduler:
        schedule: "*/1 * * * *"
        jobTemplate:
          template:
            spec:
              securityContext:
                runAsUser: 999
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              containerSecurityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL                        
      repositories:
        - name: s3-repo
          backend: s3-backend
          directory: /mongodb
          encryptionSecret:
           name: encry-secret
           namespace: demo
      addon:
        name: mongodb-addon
        tasks:
        - name: LogicalBackup
        containerRuntimeSettings:
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        jobTemplate:
          spec: 
            securityContext: 
              runAsUser: 999
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault                  