apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: mongodb-backup
spec:
  image: sayedppqq/mongodb:sayed_mongo_linux_amd64
  args:
  - backup
  - --scratch-dir=${scratchDir:=/tmp}
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --mongo-args=${mongoArgs:=}
---
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: mongodb-restore
spec: 
  image: sayedppqq/mongodb:sayed_mongo_linux_amd64
  args:
  - restore
  - --scratch-dir=${scratchDir:=/tmp}
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --mongo-args=${mongoArgs:=}