apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: mongodb-backup
spec:
  image: sayedppqq/mongodb:version-test_4.2.3_linux_amd64
  args:
  - backup
  - --scratch-dir=${scratchDir:=/tmp}
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --mongo-args=${mongoArgs:=}

---

apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: mongodb-restore
spec: 
  image: sayedppqq/mongodb:version-test_4.2.3_linux_amd64
  args:
  - restore
  - --scratch-dir=${scratchDir:=/tmp}
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --mongo-args=${mongoArgs:=}

---

apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: mongodb
spec:
  backupTasks:
  - name: mongodb-backup
    singleton: true
    function: mongodb-backup
    driver: Restic
    parameters:
    - name: mongoArgs
      usage: Specifies the database args for taking backup
      required: false
  restoreTasks:
  - name: mongodb-restore
    singleton: true
    function: mongodb-restore
    driver: Restic
    parameters:
    - name: mongoArgs
      usage: Specifies the database args for restore
      required: false
