apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: mg-restore
  namespace: demo
spec:
  target:
    name: simple7
    namespace: demo
    apiGroup: kubedb.com
    kind: MongoDB
  dataSource:
    snapshot: latest
    repository: test7
    encryptionSecret:
      name: encry-secret 
      namespace: demo
  addon:
    name: mongodb-addon
    tasks:
      - name: LogicalBackupRestore
  runtimeSettings:
    pod:
      securityContext:
        runAsUser: 999
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    container:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
                