apiVersion: storage.kubestash.com/v1alpha1
kind: BackupStorage
metadata:
  name: s3-storage
  namespace: demo
spec:
  storage:
    provider: s3
    s3:
      endpoint: ap-south-1.linodeobjects.com
      bucket: abusayed
      region: ap-south-1
      prefix: mg-arch
      secretName: s3-secret
  usagePolicy:
    allowedNamespaces:
      from: All
  deletionPolicy: WipeOut
  # runtimeSettings:
  #   pod:
  #     securityContext:
  #       runAsUser: 999
  #       runAsNonRoot: true
  #       seccompProfile:
  #         type: RuntimeDefault
  #   container:
  #     securityContext:
  #       allowPrivilegeEscalation: false
  #       capabilities:
  #         drop:
  #           - ALL