apiVersion: kubedb.dev.my.domain/v1alpha2
kind: FerretDB
metadata:
  name: ferretdb-sample-tls
  namespace: demo
spec:
  version: "1.12.1"
  authSecret:
    externallyManaged: false
  sslMode: requireSSL
  tls:
    issuerRef:
      apiGroup: "cert-manager.io"
      kind: Issuer
      name: mongo-ca-issuer
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi  
  backend:
    externallyManaged: false
    backendDB: "postgres"
  terminationPolicy: Delete
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        labels:
          release: prometheus
        interval: 10s  