apiVersion: kubedb.dev.my.domain/v1alpha2
kind: FerretDB
metadata:
  name: ferretdb-sample
  namespace: demo
spec:
  version: "1.12.1"
  authSecret:
    externallyManaged: true
    name: quick-postgres-auth
  sslMode: disabled
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi  
  backend:
    externallyManaged: true
    backendDB: "postgres"
    postgresInfo:
      serviceInfo:
        name: quick-postgres-pods
        namespace: demo
        pgPort: "5432"
  terminationPolicy: Delete