apiVersion: kubedb.com/v1alpha2
kind: PerconaXtraDB
metadata:
  name: sample-pxc
  namespace: demo
spec:
  version: "8.0.26"
  replicas: 3
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 250Mi
  terminationPolicy: WipeOut
  podTemplate:
    spec:
      initContainers:
      - name: hello
        image: alpine
        args: ["/bin/sh", "-c", "echo hello-world"] 