# services:
#   postgres:
#     image: postgres
#     environment:
#       - POSTGRES_USER=username
#       - POSTGRES_PASSWORD=password
#       - POSTGRES_DB=ferretdb

#   mongodb:
#     image: mongo
#     restart: unless-stopped
#     ports:
#       - 27018:27018

# networks:
#   default:
#     name: ferretdb

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=random
      - POSTGRES_DB=ferretdb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  ferretdb:
    #image: ghcr.io/ferretdb/ferretdb:1.13.0
    #image: ghcr.io/ferretdb/ferretdb:1.14.0
    image: ghcr.io/ferretdb/ferretdb:1.10.1
    restart: on-failure
    ports:
      - 27017:27017
      - 8088:8088
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://postgres:5432/ferretdb

networks:
  default:
    name: ferretdb

# services:

#   ferretdb:
#     image: ghcr.io/ferretdb/ferretdb
#     restart: on-failure
#     ports:
#       - 27017:27017
#     environment:
#       - FERRETDB_HANDLER=sqlite
#       - FERRETDB_SQLITE_URL=file:/data/
#     volumes:
#       - ./data:/data/
    
# networks:
#   default:
#     name: ferretdb