apiVersion: apps/v1
kind: Deployment
metadata:
  name: ferretdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ferretdb
  template:
    metadata:
      labels:
        app: ferretdb
    spec:
      containers:
        - name: postgresdb
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: random
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: ferretdb
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: db-data
        - name: ferretdb
          image: ghcr.io/ferretdb/ferretdb:1.13.0
          ports:
            - containerPort: 27017
          env:
            - name: FERRETDB_POSTGRESQL_URL
              value: postgres://127.0.0.1:5432/ferretdb
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-persistent-volume-claim