apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: demo  
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 1
      targetPort: 5432
  type: ClusterIP