apiVersion: apps/v1
kind: Deployment
metadata:
  name: ferretdb
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ferretdb
  template:
    metadata:
      labels:
        app: ferretdb
    spec:
      containers:
        - name: ferretdb
          image: ghcr.io/ferretdb/ferretdb
          ports:
            - containerPort: 27017
          env:
            - name: FERRETDB_POSTGRESQL_URL
              value: "postgres://postgres-service.demo.svc.cluster.local:1/ferretdb"
            #- name: FERRETDB_POSTGRESQL_URL
            #  value: "postgres://ha-postgres.demo.svc.cluster.local:5432/"              