apiVersion: v1
kind: Service
metadata:
  name: ferretdb-clusterip-service
  namespace: demo
spec:
  selector:
    app: ferretdb
  ports:
    - port: 27018 # The port you want to forward
      targetPort: 27018 # The port your FerretDB container is listening on
